### PR TITLE
introduce new constructor style for PHP7 support. Drop php4 support

### PR DESCRIPTION
**Pull request by TomK**
Rebased onto development as requested in #35.  Deprecates #35.

### CODE REVIEW

**Comment by TomK** [comment]
Should have mentioned:   Closes #36

**Comment by finwe** [comment]
I have just compiled PHP 4 and tried to run some examples, and I found out that there is a class constant used which causes parse error.

<code><b>Parse error</b>:  syntax error, unexpected ')', expecting '(' in <b>/home/finwe/www/_github/mpdf-mpdf/mpdf.php</b> on line <b>30496</b></code>

So I believe that it is safe to remove PHP4 constructors and "support" entirely. I'd then also vote to add public visibility to new __construct methods.

Could you please edit the PR accordingly?

**Comment by TomK** [comment]
@finwe I have pushed this for mpdf classes now.  I have omitted the fpdi classes as they are covered by @JanSlabon #47.

**Comment by finwe** [comment]
Awesome. I have a few other minor suggestions: could you please:
- remove `&` reference operators from constructor parameters,
- add `mPDF` type hints to `$mpdf` parameters,
- and remove those ugly // CONSTRUCTOR comments?

Then just push the new commits, PR should then reflect them.

**Comment by TomK** [comment]
done, only tests that fail in php7 are related to fpdi classes now.  tests pass in php54 and php56.

**Comment by finwe** [comment]
Merged, thanks!

**Pull request closed without merging**
