### PR TITLE
php 8

### PR DESCRIPTION
**Pull request by psohm**
mpdf/mpdf v8.0.7 requires php ^5.6 || ~7.0.0 || ~7.1.0 || ~7.2.0 || ~7.3.0 || ~7.4.0 -> your PHP version (8.0.0) does not satisfy that requirement.

### CODE REVIEW

**Comment by michaljusiega** [comment]
@finwe Why closed?

**Comment by finwe** [comment]
No effort whatsoever. Until CI is in the green on PHP 8, composer will not be updated.

**Comment by michaljusiega** [comment]
@finwe 
Are You Serious, really ? Why do you compare CI to user-case ? 

Let's try to install `mpdf/mpdf` on `PHP8.0` on new project.

IMHO - If passed on CI nightly, why not added to `composer.json` to increase compatibility ? Let's merge this PR and add information do README.md ...

**Comment by michaljusiega** [comment]
@finwe So let's try make CI green ?

**Comment by finwe** [comment]
Sure, feel free to have a go. Just sync the development branch with the last commits I just pushed - some of the work is done there.

**Pull request closed without merging**
