### PR TITLE
Fix Warning Undefined array key "VALUE" in Option.php

### PR DESCRIPTION
**Pull request by Shadow243**
Fixing an issue of the "Undefined array key "VALUE" notice in Option.php.
Link to the reported issue: https://app.glitchtip.com/evoludata/issues/2379545

### CODE REVIEW

**Comment by finwe** [comment]
Thanks for the PR. Though it lacks a test and more thorough explanation of what and how this should solve things. Please elaborate.

**Comment by Shadow243** [comment]
Thanks for your feedback.

Regarding the issue with the provided link, it is currently protected by credentials, making it inaccessible for a complete understanding. To enhance clarity and provide a more comprehensive view of the problem, I have included a screenshot that offers additional context and detailed insights into the issue. This screenshot serves as a valuable supplement to the link and will aid in a more thorough comprehension of the matter at hand.
Screenshot 2023-10-18 at 23 50 06

**Comment by finwe** [comment]
This does not provide any meaningful additional information at all.

**Comment by Shadow243** [comment]
According to the function: `public function open($attr, &$ahtml, &$ihtml)
	{
		$this->mpdf->lastoptionaltag = '';
		$this->mpdf->selectoption['ACTIVE'] = true;
		$this->mpdf->selectoption['currentSEL'] = false;
		if (empty($this->mpdf->selectoption)) {
			$this->mpdf->selectoption['MAXWIDTH'] = '';
			$this->mpdf->selectoption['SELECTED'] = '';
		}
		if (isset($attr['SELECTED'])) {
			$this->mpdf->selectoption['SELECTED'] = '';
			$this->mpdf->selectoption['currentSEL'] = true;
		}
		if (isset($attr['VALUE'])) {
			$attr['VALUE'] = UtfString::strcode2utf($attr['VALUE']);
			$attr['VALUE'] = $this->mpdf->lesser_entity_decode($attr['VALUE']);
			if ($this->mpdf->onlyCoreFonts) {
				$attr['VALUE'] = mb_convert_encoding($attr['VALUE'], $this->mpdf->mb_enc, 'UTF-8');
			}
		}
		$this->mpdf->selectoption['currentVAL'] = $attr['VALUE'];
	}`

There is a condition checking if $attr['VALUE'] is set but while assigning $attr['VALUE'] to $this->mpdf->selectoption['currentVAL'] there is no.

We could change it like this: $this->mpdf->selectoption['currentVAL'] = $attr['VALUE'] ?? null; instead of adding it inside the condition. The issue here is that we are trying to access an undefined array key VALUE

**Comment by finwe** [comment]
Cool, now add a test to the PR with a code example that is affected by this fix. See test/Issues for examples.

**Comment by Shadow243** [comment]
Missing Test added.

**Comment by finwe** [comment]
This way of testing works, I guess, but I still would like a test to present an actual failing HTML snippet.

**Comment by Shadow243** [comment]
Test with failing HTML snippet added too. 

The HTML code 
```
<select>
 <option value="this is valid">Option 1</option>
 <option selected>Option 2</option>
</select>
```
contains an <option> element without the 'value' attribute defined, and this specific structure is the direct cause of the error. 

This test should pass without applied correction.

```
public function testWithFailingHtmlSnippet()
{
   $mpdf = $this->mpdf;

   $html = '<select><option value="this is valid">Option 1</option><option selected>Option 2</option>. </select>';

   try {
	$mpdf->WriteHTML($html);
   } catch (\Throwable $th) {
	$this->assertEquals('Undefined array key "VALUE"', $th->getMessage());
   }
}
```

**Comment by Shadow243** [comment]
I changed also this: 
```
$this->mpdf->selectoption['currentVAL'] = $attr['VALUE'] ?? null; 
```
to 
```
$this->mpdf->selectoption['currentVAL'] = isset($attr['VALUE']) ? $attr['VALUE'] : null;
```
to support php version 5.x

**Comment by finwe** [comment]
Great. Now that we know what HTML causes this, let's make this even more up to standard:

> [value](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/option#value)
> The content of this attribute represents the value to be submitted with the form, should this option be selected. If this attribute is omitted, the value is taken from the text content of the option element.

So, when the value attribute is not set, the textual value of the element should be used. Can we easilly set that instead of a default null?

**Comment by Shadow243** [comment]
Requested updates Done.

With this, we are putting the textual value instead of null:
```
$this->mpdf->selectoption['currentVAL'] = isset($attr['VALUE']) ? $attr['VALUE'] : $ahtml[$ihtml + 1];
```

**Comment by Shadow243** [comment]
@finwe I'm waiting for your review to make sure every thing is now okay.

**Pull request merged**
