### PR TITLE
Allow psr/log v2

### PR DESCRIPTION
**Pull request by snapshotpl**
v3 after merge this one.

### CODE REVIEW

**Comment by finwe** [comment]
Do not add unrelated gitignore items.

**Comment by finwe** [comment]
Any particular reason not to allow v3 at the same time?

**Comment by finwe** [comment]
Also, please squash the commits to one.

**Comment by snapshotpl** [comment]
v3 fails hard because:
```
Fatal error: Declaration of Mpdf\Mpdf::setLogger(Psr\Log\LoggerInterface $logger) must be compatible with Psr\Log\LoggerAwareInterface::setLogger(Psr\Log\LoggerInterface $logger): void in /usr/src/myapp/src/Mpdf.php on line 1569
```

Probably not impossible to support v3 before we not drop php under 7.1

**Comment by finwe** [comment]
Ack. I'm OK with that. What is the reason for including the testlogger?

**Comment by snapshotpl** [comment]
`RemoteContentTest` need test implementation

**Comment by finwe** [comment]
Hmm... Can you create an implementation in a separate file under Mpdf namespace to remove the hassle with bracketed namespaces in _functions_ file and then use that implementation?

**Comment by snapshotpl** [comment]
Not time for this perfection. However we can merge as it and separate if have time

**Comment by finwe** [comment]
No time for merging this imperfection.

**Comment by snapshotpl** [comment]
Too bad.

**Comment by finwe** [comment]
Thanks for the current effort, anyway

**Pull request closed without merging**
