### PR TITLE
Allow any PHP version on Travis

### PR DESCRIPTION
**Pull request by jayvdb**

### CODE REVIEW

**Comment by finwe** [comment]
No, sorry. I want to allow only versions against which this was properly tested and is guaranteed to be working.

**Comment by jayvdb** [comment]
The build is failing because `latest` is being built.
I guess there is some flag to override the composer.json php restrictions.

**Comment by finwe** [comment]
Oh, I see. I'll try to take a look.

**Comment by finwe** [comment]
Nice catch with that --ignore-platform-reqs, But I'd allow failures for hhvm and nightly.

**Comment by jayvdb** [comment]
I can understand allowing failure on `nightly`, as it is a moving target, however I do not agree wrt hhvm, which is always the latest release on Ubuntu precise, which is not a new version.  It is 3.6.* which is very stable.

**Comment by finwe** [comment]
It's just that mPDF is not regularly tested on HVVM and not guaranteed to be compatible with it. I know that it most likely will be, but for the time being, at least untill 7.0 is stable and out, I'd like to not to worry that failing hvvm build will distract the development away from more urging matters.

**Comment by jayvdb** [comment]
Done

**Comment by finwe** [comment]
Merged, thanks!

**Pull request merged**
