### PR TITLE
PHP oop syntax fixes

### PR DESCRIPTION
**Pull request by machour**
This PR:
  * Replaces old `var` properties declaration with `public`
  * Adds `public` to methods without access modifier

I switched everything to public to avoid any BC breaks, separated commits & successfully ran tests.

### CODE REVIEW

**Comment by Klap-in** [comment]
Not sure, but it could be that the `var` instead of `public` property was used for some bookkeeping, with respect to future refactorizations.

**Comment by machour** [comment]
@Klap-in thanks for this insight, haven't thought of it!
Maybe this commit can be used for the book keeping instead: https://github.com/mpdf/mpdf/pull/542/commits/7ab0601c161f0b9ff60365249572b3d1548abd08
😄

**Comment by finwe** [comment]
Thanks, but I'd really like to have the `var` keywords right there in the open to cause pain every time anyone comes across them so that he/she knows that this is still unaccounted for and needs *real* fixing :)

**Comment by machour** [comment]
@finwe I'm curious what would the _real_ fixing look like? Are you talking about getting rid of this properties, or picking `private` or `public` depending on the need?

**Comment by finwe** [comment]
The latter - picking private or public depending on the needs. Also see https://github.com/mpdf/mpdf/issues/502

**Comment by machour** [comment]
Thank you! I'll take a closer look at the project's milestones.

**Pull request closed without merging**
