### PR TITLE
Add support for page-break-before: avoid; and page-break-after: avoid; for <tr> elements

### PR DESCRIPTION
**Pull request by carli2**
This code is sponsored by Launix (https://launix.de) and released under GPL 2.0

In order to not get into fork hell, we appreciate a fast release of the feature in the next minor version.

### CODE REVIEW

**Comment by finwe** [comment]
Thanks for the PR. in order to be incorporated, please add a reasonable test coverage and include a changelog entry.

**Comment by carli2** [comment]
Thanks to the unit tests I found a copy&paste error, so the change should be fine now.

**Comment by finwe** [comment]
Can you also please move the test to a separate class under Issues/? Thanks.

**Comment by finwe** [comment]
You should be able to check CS locally easily by just running `composer cs`.

**Comment by carli2** [comment]
> You should be able to check CS locally easily by just running `composer cs`.

which issue number shall I use?

**Comment by finwe** [comment]
Well, this one, 2004

**Comment by finwe** [comment]
Great, thanks! Can you also prepare a PR to update the supported CSS docs at https://github.com/mpdf/mpdf.github.io/blob/master/css-stylesheets/supported-css.md?

**Comment by carli2** [comment]
> Great, thanks! Can you also prepare a PR to update the supported CSS docs at https://github.com/mpdf/mpdf.github.io/blob/master/css-stylesheets/supported-css.md?

done

**Pull request merged**
