### PR TITLE
fixed issue if rowspan not a number

### PR DESCRIPTION
**Pull request by JagdishKuma**

### CODE REVIEW

**Comment by finwe** [comment]
Thanks for a PR. What issue? Per contribution guidelines, provide a unit test covering the fix in question.

**Comment by JagdishKuma** [comment]
> Thanks for a PR. What issue? Per contribution guidelines, provide a unit test covering the fix in question.

Hi 
Earlier someone fixed the issue for COLSPAN and now I am getting the same issue for ROWSPAN so I applied the same fix for ROWSPAN.
The issue occurs while parsing and if inside the ROWSPAN has a value like rowspan="“4&quot;"  means if rowspan has a value other than number then the issue occurs.
So I added this fixed.
Thanks

**Comment by finwe** [comment]
You still need to add a test covering the change.

**Comment by JagdishKuma** [comment]
> [ ](/JagdishKuma)

Can you share some samples how I can share test covering the change?

**Comment by finwe** [comment]
See the commit of the colspan change https://github.com/mpdf/mpdf/commit/b399c5a319d76339cdc039eaee3b20683cfcae0d

**Comment by JagdishKuma** [comment]
> See the commit of the colspan change [b399c5a](https://github.com/mpdf/mpdf/commit/b399c5a319d76339cdc039eaee3b20683cfcae0d)

test coverage class added let me know if require more from my side.

**Comment by JagdishKuma** [comment]
thanks for the merge PR.
can you tell me how much time it will take to merge PR on the master.

**Comment by finwe** [comment]
Released 8.2.0.

**Comment by JagdishKuma** [comment]
Okay Thanks

**Comment by JagdishKuma** [comment]
Hi @finwe 
Is mpdf Supports PDF A-3b I tried everything which is in Maunal.
However, I am not able to generate PDF A-3b.
I am getting PDF A-1b Only.

**Comment by finwe** [comment]
@JagdishKuma This is not a troubleshooting location. And I don't know.

**Pull request merged**
