### PR TITLE
Fix issue#529: Undefined index: max_bottom

### PR DESCRIPTION
**Pull request by mwetzl**
Check for a nonexistent value: $this->ColDetails[$s['col']]['max_bottom']
Similar code can be found in line 26789

### CODE REVIEW

**Comment by Klap-in** [comment]
Can you complete the pull request with an unit test? For examples of unit tests you can have a look at https://github.com/mpdf/mpdf/tree/development/tests/Issues
Thanks in advance!

**Comment by MatthiasKuehneEllerhold** [comment]
Could you please include the fix for the other line too? Its line 27029 in version v7.1.4 and line 27093 on branch development.

**Comment by davidraijmakers** [comment]
Tested this, and this fixes the critical error in 7.1.4. Is this being merged soon?

**Comment by finwe** [comment]
Line 27093 sanitized in a subsequent commit.

**Comment by MatthiasKuehneEllerhold** [comment]
Thx!

**Pull request merged**
