### PR TITLE
Psr logger 3.0 support

### PR DESCRIPTION
**Pull request by TuxBoy**
Hi,

In this PR, I propose the support of the psr logger 3.0 which adds return typing on the methods `setLogger()`.

I used the `LoggerAwareTrait` trait provided by the psr library to ease compatibility between the different possible versions.

### CODE REVIEW

**Comment by finwe** [comment]
Not possible ATM. Not mentioning all unnecessarily changed lines. 

https://github.com/mpdf/mpdf/issues/1622

**Comment by TuxBoy** [comment]
Even with the use of the trait? is it to be compatible with older versions of PHP?

**Comment by finwe** [comment]
Yes, as mentioned in linked Issue.

**Comment by TuxBoy** [comment]
With the `LoggerAwareTrait``trait of the logger, we are still compatible with the different versions?

**Comment by finwe** [comment]
No, there is no timeline when to remove older PHP versions support.

**Comment by finwe** [comment]
For reference https://github.com/mpdf/mpdf/issues/1637

**Comment by TuxBoy** [comment]
alright, thanks for the passed time and sorry ;)

**Comment by finwe** [comment]
No worries, thanks for the effort.

**Pull request closed without merging**
