### PR TITLE
SVG styles issue 

### PR DESCRIPTION
**Pull request by antman3351**
Fixes mpdf#450 SVGs made with Adobe Illustrator are black

### CODE REVIEW

**Comment by finwe** [comment]
Hi, thanks for the PR.

Please, fix lint issues, add a test with example SVG failing without this change, add a changelog entry and squash the commits to one.

**Comment by antman3351** [comment]
Hey, I'm a bit busy at the moment I'll get on to it as soon as I have a moment.

**Comment by antman3351** [comment]
Hi, I've:
- Added a unit test,
- Added an entry to the change log
- Changed spaces to tabs and removed white spaces for the lint
- I did my best to squash the commits, but I think I just ended up with more commits 😐
(I also changed the code a bit)

**Comment by antman3351** [comment]
Epic fail... I had to make annother change and ended up not being able to push to github any more... So i deleted the repository and recreated a clean version.

**Pull request closed without merging**
