### PR TITLE
Added function to show and hide barcode numbers

### PR DESCRIPTION
**Pull request by danieljausovec**
Added feature to development version.

### CODE REVIEW

**Comment by finwe** [comment]
I don't know if hiding only bottom numbers is an expected behaviour when setting a document-global variable showBarcodeNumbers.

All this seems to me more like a hackish solution, one large if block.

Furthermore, on page 3 of the example file are missing their right part.

shot_160708_124719

Please revise.

**Comment by danieljausovec** [comment]
I don't know if is there any better solution for this. I have fixed now all.
Please check and comment.

**Comment by finwe** [comment]
That's better. Please, remove changes to lines not affecting the scope of this feature (eg. indentation in Mpdf.php:3783 etc) and squash commits to one. Then force push.

Then allow me some time to incorporate this. Thanks for contributing!

**Comment by danieljausovec** [comment]
All done. Thanks.

**Comment by finwe** [comment]
One more thing - could you amend the author in the commit to your github-registered e-mail address? Or register the address in the commit to your github account? So that the commit shows your icon?

**Comment by danieljausovec** [comment]
How to do that? Sorry, i use github first time on this way.

**Comment by finwe** [comment]
It's more of a git-thing. Either do 

```
$ git commit --amend --author="Daniel Jausovec <your-github-email-adress>"
$ git push --force
```

or add the bebetter.si e-mail address to your e-mails here at https://github.com/settings/emails

**Comment by danieljausovec** [comment]
Done. Thanks.

**Comment by finwe** [comment]
Excellent!

**Comment by finwe** [comment]
I have rebased the code to current `development` branch. It doesn't function properly, it hides bottom numbers even when no changes are made in the configuration.

If you want to see this through, please use the [`barcode-hide-numbers`](https://github.com/mpdf/mpdf/tree/barcode-hide-numbers) branch of the main repo to base your fixes upon. Then submit a new PR.

In the meantime, I am closing this as outdated and faulty.

**Pull request closed without merging**
