### PR TITLE
Add support for PHP 8.4.*

### PR DESCRIPTION
**Pull request by mkoprek**
Simply just add support for PHP 8.4.*

### CODE REVIEW

**Comment by finwe** [comment]
How did you simply just test this, given that the stable is not even out and therefore composer cannot be run without ignores given this composer.json?

**Comment by mkoprek** [comment]
Well I did not. I was sure there will be some pipeline started on this pull request for all checks.

**Comment by finwe** [comment]
Meh

**Comment by phpfui** [comment]
I just tested this under 8.4.0RC3 and it works fine.

Can we get a version tag for this?  Then the library will be ready to go for 8.4 release.

Thanks!

**Pull request merged**
