### PR TITLE
bugfix in Otl class

### PR DESCRIPTION
**Pull request by salah11172**
bugix in otl class when print pdf

### CODE REVIEW

**Comment by finwe** [comment]
Thanks for the PR. Add a unit test failing before and passing after your change. See `tests/Issues` directory in the repo.

**Comment by salah11172** [comment]
This means that he will accept or not ?

**Comment by finwe** [comment]
I don't know yet, I need to explore the example code in the test case.

**Comment by finwe** [comment]
Closing as stale. Can reopen when the test is added.

**Pull request closed without merging**
