### PR TITLE
Add AutoPrint

### PR DESCRIPTION
**Pull request by dansleboby**
Add AutoPrint() to allow pdf to prompt print window without JS method witch is unreliable

Credit: https://github.com/MrRio/jsPDF/blob/master/src/modules/autoprint.js

### CODE REVIEW

**Comment by finwe** [comment]
Thanks for the PR. There is no need to create a new writer, add the functionality to metadata writer.

**Comment by finwe** [comment]
Also please prepare a documentation for the new method at https://github.com/mpdf/mpdf.github.io

**Comment by dansleboby** [comment]
Good I will make the requested change very soon 👍

**Comment by finwe** [comment]
Closing as stale. Will gladly reopen when requested update is provided.

**Pull request closed without merging**
