### PR TITLE
Fix bug #724

### PR DESCRIPTION
**Pull request by sreenadh**

### CODE REVIEW

**Comment by jakejackson1** [comment]
Thanks for your contribution. Mpdf still supports PHP5.6 so we are unable to use the null coalesce at this time. Also, all PRs require appropriate unit tests. Please see https://github.com/mpdf/mpdf/tree/development/tests/Issues for examples.

**Comment by sreenadh** [comment]
@jakejackson1 Done 👍

**Comment by finwe** [comment]
Why introducing a new static method instead of just using get with null as the third parameter?

**Comment by finwe** [comment]
Thanks!

**Pull request merged**
