### PR TITLE
Barcode quiet zones customization

### PR DESCRIPTION
**Pull request by vincenzo-mennella-shippypro**
Adds the functionality requested into #1430.

All existing tests passed

### CODE REVIEW

**Review by finwe — CHANGES_REQUESTED** [review]
This seems OK, just a few changes in addition to failing lint:

- Use null as a default/empty value, the empty string is quirky.
- Use nicer, more verbose and meaningful HTML parameter name and function parameter names and array keys. eg. `$quietZoneLeft`, `quiet_zone_left` and `QUIET_ZONE_LEFT`
- Add a test actually using the added code, with a code example that can be reproduced and perhaps even used in documentation

**Comment by finwe** [comment]
Please, rebase instead of merging in upstream.

**Review by finwe — CHANGES_REQUESTED** [review]
Great! Just one last bit, please use `=== null` comparison instead of `is_null`.

**Review by finwe — CHANGES_REQUESTED** [review]
When fixing the lint, please squash commits to one, I'll merge right after.

**Comment by vincenzo-mennella-shippypro** [comment]
Corrected the lint (sorry, didn't see it!)

**Comment by finwe** [comment]
Thanks for quick responses.

**Comment by vincenzo-mennella-shippypro** [comment]
Thank you for checking! Do you have an ETA for tagging this?

**Comment by finwe** [comment]
I tend to create releases when a few features/fixes pile up, so no ETA.

**Pull request merged**
