### PR TITLE
Fix error during 'float' and 'page-break-inside'

### LINKED ISSUE #785: Error during float and page-break-inside
I have created div with `page-break-inside: avoid ` style, it works OK. But if inside is another div which is floating, then I got error. If I do floating without page-break-inside, it works too. Only those 2 approaches together do not work.
Code is below, I have **PHP 7.2.3** and **mPDF 7.1.0**

#### HTML:
```
<div style="page-break-inside: avoid !important;">
  <p>Signed <?php echo current_time('d.m.Y'); ?></p> 

  <div>
    <div style="float: left, width: 50%;">_________________________<br>Me</div>
    <div style="float: left, width: 50%;">_________________________<br>You</div>
  </div>  
  <div style="clear: both"></div> 
</div>
```

#### PHP:
```
$mpdf = new \Mpdf\Mpdf([
    'mode'              => 'utf-8',
    'format'            => 'A4',
    'default_font_size' => 14,
]);
$mpdf->img_dpi = 300;
$mpdf->dpi = 96;
$mpdf->SetHTMLFooter('<div style="text-align:center;font-size: 9pt;">Page {PAGENO} (total {nbpg})</div>');
$mpdf->WriteHTML($invoiceContent);
$mpdf->output();
```

Error which I see in final PDF file is
```
Warning:  A non-numeric value encountered in vendor\mpdf\mpdf\src\Mpdf.php on line 16807
Warning:  A non-numeric value encountered in vendor\mpdf\mpdf\src\Mpdf.php on line 16807
Warning:  A non-numeric value encountered in vendor\mpdf\mpdf\src\Mpdf.php on line 6297
Warning:  A non-numeric value encountered in vendor\mpdf\mpdf\src\Mpdf.php on line 6411
Warning:  A non-numeric value encountered in vendor\mpdf\mpdf\src\Mpdf.php on line 16807
Warning:  A non-numeric value encountered in vendor\mpdf\mpdf\src\Mpdf.php on line 6498
Warning:  A non-numeric value encountered in vendor\mpdf\mpdf\src\Mpdf.php on line 16807
Warning:  A non-numeric value encountered in vendor\mpdf\mpdf\src\Mpdf.php on line 16807
Warning:  A non-numeric value encountered in vendor\mpdf\mpdf\src\Mpdf.php on line 16807
Warning:  A non-numeric value encountered in vendor\mpdf\mpdf\src\Mpdf.php on line 6297
Warning:  A non-numeric value encountered in vendor\mpdf\mpdf\src\Mpdf.php on line 6411
Warning:  A non-numeric value encountered in vendor\mpdf\mpdf\src\Mpdf.php on line 9139
Warning:  A non-numeric value encountered in vendor\mpdf\mpdf\src\Mpdf.php on line 18182
Warning:  A non-numeric value encountered in vendor\mpdf\mpdf\src\Mpdf.php on line 18306
Warning:  A non-numeric value encountered in vendor\mpdf\mpdf\src\Mpdf.php on line 18697
Warning:  A non-numeric value encountered in vendor\mpdf\mpdf\src\Mpdf.php on line 18715
Warning:  A non-numeric value encountered in vendor\mpdf\mpdf\src\Mpdf.php on line 18721

```

### PR DESCRIPTION
**Pull request by lucassouzavieira**
Resolve #785

### CODE REVIEW

**Comment by finwe** [comment]
Thanks for the PR! Can you please remove all changes unrelated to the fix, rebase on development and squash commits to one?

**Comment by lucassouzavieira** [comment]
@finwe, done.

**Comment by omoustaouda** [comment]
Hello,
do we have any update on this PR?

If I can help with anything, for having the PR merged, just let me know,
happy to do that.

**Comment by finwe** [comment]
I've tested the code and I think this change is a hacky quick fix - the value that causes the error is an empty string. `''`. So I've changed places in code where `$mpdf->kt_y00` was set to an empty string to 0 as a neater fix. The test passes, the fix is merged in 9806187.

**Comment by finwe** [comment]
Thanks for the PR!

**Pull request closed without merging**
