### PR TITLE
Update FPDI to 1.6.0

### PR DESCRIPTION
**Pull request by blueliquiddesigns**
Original PR from JanSlabon (https://github.com/mpdf/mpdf/pull/47) merged in the development branch and had unit tests updated.

### CODE REVIEW

**Comment by finwe** [comment]
Well, thanks! But could you please squash the commits or use `rebase`? I would like to stick to [a simple git branching model](https://gist.github.com/jbenet/ee6c9ac48068889b0912) and avoid merge hell.

**Comment by finwe** [comment]
And also, composer.lock should be ommited from the repository (I missed it with the Unit testing PR), this is now fixed.

**Comment by finwe** [comment]
And also, indentation of mpdf.php is all messed up. Please stick with one tab per level.

**Comment by blueliquiddesigns** [comment]
Hmm. Looks like the tab issues was caused by the original PR – I just merged it into the dev branch with sorted through any conflicts. 

Tabs should be fixed now , the PR has been rebased on the development branch and all the unit tests work. Let me know if there's anything else needed.

**Comment by finwe** [comment]
Merged, thanks!

**Pull request closed without merging**
