### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by kravcik**
Typos ;

### CODE REVIEW

**Comment by finwe** [comment]
Thanks! Fixed manually, was faster.

**Comment by kravcik** [comment]
Also i noticed, when I use this example - version 6.1.0 from composer hasnt this namespace. :)

**Comment by finwe** [comment]
Yes, the default README file is for development branch. README for 6.1.0 does not contain the example https://github.com/mpdf/mpdf/blob/v6.1.0/README.md

**Comment by finwe** [comment]
@kravcik I have added [a note](https://github.com/mpdf/mpdf/commit/e6c6f13b62c8b552a6e960813be3cde278c1e25e) to the README file.

**Pull request closed without merging**
