### PR TITLE
Remove redundant PHP endings.

### PR DESCRIPTION
**Pull request by ram4nd**

### CODE REVIEW

**Comment by danielhjames** [comment]
In classes/barcode.php lines 432 and 549 your pull request changes '£K' to '�K' - is this intentional?
See also classes/svg.php where you have similar issues with French characters.

**Comment by ram4nd** [comment]
Really, I did not notice. That would imply that the files in the library
are not UTF-8 encoded. So that conversion would also be necessary.

On 8 June 2015 at 18:14, Daniel James <notifications@github.com> wrote:

> In classes/barcode.php lines 432 and 549 your pull request changes '£K' to
> '�K' - is this intentional?
> See also classes/svg.php where you have similar issues with French
> characters.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mpdf/mpdf/pull/21#issuecomment-110033714>.
>



-- 
Ra Mänd

**Comment by danielhjames** [comment]
On my system the mPDF files appear to be ISO-8859 encoded with CRLF line terminators. We worked around the CRLF issue with https://github.com/mpdf/mpdf/commit/9f97933ad39ef2a113544e6924de37863a52e86c

**Comment by ram4nd** [comment]
Well the files should be converted to UTF-8. Workaround is not a solution
here.

On 8 June 2015 at 18:51, Daniel James <notifications@github.com> wrote:

> On my system the mPDF files appear to be ISO-8859 encoded with CRLF line
> terminators. We worked around the CRLF issue with 9f97933
> <https://github.com/mpdf/mpdf/commit/9f97933ad39ef2a113544e6924de37863a52e86c>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mpdf/mpdf/pull/21#issuecomment-110051069>.
>



-- 
Ra Mänd

**Comment by danielhjames** [comment]
Consider that if a developer is working on Windows, if we removed all CRLF then every single file would show as a changed file, requiring a full review. Personally I don't think that would be such a bad thing, if we also converted the entire project to UTF-8 at the same time.

**Comment by ram4nd** [comment]
It would. You could use meld diff viewer for an example. Or do it yourself
if you can. The library is lacking consistency and coding standards. Would
be nice to get it cleaned up a bit, so future developments would not be so
painful.

On 9 June 2015 at 11:46, Daniel James <notifications@github.com> wrote:

> Consider that if a developer is working on Windows, if we removed all CRLF
> then every single file would show as a changed file, requiring a full
> review. Personally I don't think that would be such a bad thing, if we also
> converted the entire project to UTF-8 at the same time.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mpdf/mpdf/pull/21#issuecomment-110279572>.
>



-- 
Ra Mänd

**Comment by finwe** [comment]
Same work without encoding changes is contained in https://github.com/mpdf/mpdf/pull/31, closing this.

**Pull request closed without merging**
