### PR TITLE
Bugfix with utf8 char and Mpdf/Tag class not found

### PR DESCRIPTION
**Pull request by fglueck**

### CODE REVIEW

**Comment by finwe** [comment]
Missing a test failing prior to this change.

**Comment by finwe** [comment]
Related Issue https://github.com/mpdf/mpdf/issues/979

**Comment by fglueck** [comment]
```
  private function getTagInstance($tag)   **<- if $tag is ''**
  {
        $className = self::getTagClassName($tag); **<- this generates 'Mpdf\Tag\'**
        if (class_exists($className)) { **<- this call the autoloader (query all pathes ... and if the autoloader can't find the file an error**
          return new $className(
            $this->mpdf,
            $this->cache,
            $this->cssManager,
            $this->form,
            $this->otl,
            $this->tableOfContents,
            $this->sizeConverter,
            $this->colorConverter,
            $this->imageProcessor,
            $this->languageToFont
          );
        }
      }
  }
```

**Comment by finwe** [comment]
Not helpful. Create a unit test with a code sample actually reproducing this behaviour.

**Pull request closed without merging**
