### PR TITLE
Dont destroy hyperlinks / annotations on importing pages

### LINKED ISSUE #900: Merging PDF Files destroys external links
### I found this bug
Merging multiple PDF files into one PDF using the snippet below destroys all links (internal and external).

### This is mPDF and PHP version and environment (server/fpm/cli etc) I am using
* PHP 7.2.10
* Mpdf 7.1.6

### This is a PHP code snippet I use

```
<?php
$mpdf->SetImportUse();
foreach ($pdfDocuments as $pdfDocument) {
    $tempName  = tempnam($tempDir, 'merge');
    file_put_contents($tempName, $pdfDocument);
    $pageCount = $mpdf->SetSourceFile($tempName);

    for ($page = 1; $page <= $pageCount; $page++) {
        $mpdf->AddPage();
        $template = $mpdf->ImportPage($page);
        $mpdf->UseTemplate($template);
    }

    unlink($tempName);
}

$mpdf->SetTitle($title);

return $mpdf->Output('', 'S');
```

### This is a HTML/CSS code snippet I use

```
<html>
<body>
<a href="https://www.example.org">This ia a test link</a>
</body>
</html>
```

A solution for FPDI is offered here: https://gist.github.com/andreyvit/2020422#gistcomment-317454
I've adapted it for mpdf and it works. Do you want me to provide a PR or will this be fixed with fpdi 2.x automatically?

### PR DESCRIPTION
**Pull request by MatthiasKuehneEllerhold**
Fixes #900

### CODE REVIEW

**Comment by Klap-in** [comment]
A more general note, could you implement unit tests like your case from #900? For examples of other tests, you could have a look at: https://github.com/mpdf/mpdf/tree/development/tests

**Comment by finwe** [comment]
Thanks for the PR! Before a more thorough review a few remarks/questions:

- This will be applicable only with FPDIv1 which will be replaced with v2 in mPDF 8.x
- Do we want to have this ported also for FPDIv2 or remade only for FPDIv2?

**Comment by MatthiasKuehneEllerhold** [comment]
@Klap-in Will do!
@finwe This is strictly FPDIv1 only. I had a quick look at FPDIv2 and couldnt quite figure out how it'll work there (I'm not the original author of this fix, see my comments in #900!). 
I'll take a closer look tomorrow.

For me (personally) it'd be fine if you'd only want this for FPDIv2 (mpdf 8.x). We're using this workaround until then.

**Comment by MatthiasKuehneEllerhold** [comment]
Tests added and spaces with tabs replaced.

**Comment by guillome2k** [comment]
[test pdf link.pdf](https://github.com/mpdf/mpdf/files/2836421/test.pdf.link.pdf)

Error:
Notice: Undefined index: /Type in ...\vendor\mpdf\mpdf\src\Mpdf.php on line 27176
Notice: Undefined index: /Type in ...\vendor\mpdf\mpdf\src\Mpdf.php on line 27176
Notice: Undefined index: /Type in ...\vendor\mpdf\mpdf\src\Mpdf.php on line 27176
Notice: Undefined index: /Type in ...\vendor\mpdf\mpdf\src\Mpdf.php on line 27176

**Comment by guillome2k** [comment]
Is this fixed already? I really hope so

**Comment by finwe** [comment]
@guillome2k is the issue closed?

**Comment by MatthiasKuehneEllerhold** [comment]
The PDF from @guillome2k still leads to this problem and I'm unsure how to fix this because as I said in #900 I'm not the original author of the fix nor do I have any knowledge of PDF internals.
 I've added `isset()` - Checks, but sadly the links wont work after an import. 

So while this PR doesnt fix @guillome2k links, it fixes the import of normal hyperlinks.

**Comment by finwe** [comment]
Closing as replaced by #1002

**Pull request closed without merging**
