### PR TITLE
Corrected usage example.

### PR DESCRIPTION
**Pull request by daveismyname**

### CODE REVIEW

**Comment by finwe** [comment]
No. https://github.com/mpdf/mpdf/pull/254

**Comment by daveismyname** [comment]
where is the correct usage example for https://packagist.org/packages/mpdf/mpdf that page for the latest tag 6.1.2 uses this which is wrong.

```
require_once __DIR__ . '/vendor/autoload.php';

$mpdf = new \Mpdf\Mpdf();
$mpdf->WriteHTML('<h1>Hello world!</h1>');
$mpdf->Output();
```

Surely point to an working example would stop users wasting their time and stop wasting your time to point out something you already know. At the very least add a note to say as such.

**Comment by finwe** [comment]
As noted many times all around: https://mpdf.github.io/

**Comment by daveismyname** [comment]
Can you not see my point, that the readme that is displayed on https://packagist.org/packages/mpdf/mpdf illustrates a usage example not meant for that version. So it serves no useful purpose when looking on packagist.

I'll leave it there. Take this point or not your choice.

**Comment by finwe** [comment]
I see your point, but that is more of a Packagist problem, not displaying README accordingly to the last stable version. The README is in sync with code. It even contains a nice note at the beginning (not mentioning Packagist explicitly, but you are surely all inteligent people).

What is definitely not a correct solution is to change README in development branch to contradict code in that branch.

**Comment by finwe** [comment]
And Packagist people are not planning to change that: https://github.com/composer/packagist/issues/738#issuecomment-257302639

**Pull request closed without merging**
