### PR TITLE
updated functions.php - adding checks if dd() function already exists.

### PR DESCRIPTION
**Pull request by pure4499**
adding checks if dd() function already exists.

### CODE REVIEW

**Comment by finwe** [comment]
Thanks!

**Comment by budirec** [comment]
Yes, I don't want to use dev  master, problem is a third-party that I use using dev master

**Comment by finwe** [comment]
They're a bad third party! :) Did you try to talk them out of it?

**Comment by budirec** [comment]
Could be a bad third-party, it's pretty much dead I think. That's why I decide to comment here :) 
Thanks for the quick update though

**Pull request closed without merging**
