### PR TITLE
Fixes issue 1320: First header of named page is added twice

### PR DESCRIPTION
**Pull request by antman3351**
Fixes issue 1320: First header of named page is added twice

### CODE REVIEW

**Comment by finwe** [comment]
Thanks, very well executed PR and the change seems OK. 

Can you please change the commit message to common format `(Closes #<issue>)` at the end, also add the changelog entry to the end of the list and then squash to the PR? 

I'll merge then. Thanks!

**Comment by antman3351** [comment]
Hi Finwe,
Thanks!
I made the changes as requested, is it correct ? 
Also I'm working on another PR to add a feature does the change always go at the end on the change log? (p.s. this should be added to the contributing.md)
Thanks, Antonio.

**Comment by finwe** [comment]
The commit message still has the former format. Please change to something like `First header of named page is not added twice (#Closes 1320)`

**Comment by antman3351** [comment]
Ah ok! It should be sorted now =)

**Pull request merged**
